import React, { useState } from 'react'
import Head from 'next/head'
import { DarkContextProvider } from '../src/component/DarkContext'

import Main from '../src/component/Main'
import Nav from '../src/component/Nav'

import '../styles/reset.scss'
import '../styles/base.scss'

function MyApp({ Component, pageProps }) {
  const [isDark, setDark] = useState(false)
  const darkConfig = {
    value: isDark,
    set: setDark,
  }

  return (
    <>
      <Head>
        <title>Rich Hastings</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DarkContextProvider isDark={darkConfig}>
        {/* <Nav /> */}
        <Main>
          <Component {...pageProps} />
        </Main>
      </DarkContextProvider>
    </>
  )
}

export default MyApp
