import React, { useEffect, useState } from 'react'
import Head from 'next/head'
import { DarkContextProvider } from '../src/component/DarkContext'
import useLocalStorage from '../src/hook/useLocalStorage'

import Main from '../src/component/Main'
import Nav from '../src/component/Nav'
import CSSVariables from '../src/component/CSSVariables'

import '../styles/reset.scss'
import '../styles/base.scss'

const App = ({ Component, pageProps }) => {
  const [mode, setMode] = useLocalStorage('mode', 'light')

  const darkConfig = {
    value: mode,
    set: setMode,
  }

  return (
    <>
      <Head>
        <title>Rich Hastings</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DarkContextProvider data={darkConfig}>
        <CSSVariables />
        <Nav />
        <Main>
          <Component {...pageProps} />
        </Main>
      </DarkContextProvider>
    </>
  )
}

export default App
