import Head from 'next/head'

import Main from '../src/component/Main'
import Home from '../src/component/Home'

const HomePage = () => (
  <>
    <Head>
      <title>Rich Hastings</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Main>
      <Home />
    </Main>
  </>
)

export default HomePage
